# Config
@plate = 30F88251
@type = 1
@phpsessid = jmg7m23ttkho70rap0fs6evgb0
@captcha = rtz4rv

### Get captcha image, also cookie too
GET https://www.csgt.vn/lib/captcha/captcha.class.php

### Request violations
POST www.csgt.vn/
     ?mod=contact&
     task=tracuu_post
     &ajax
Cookie: PHPSESSID={{phpsessid}}
content-type: application/x-www-form-urlencoded

BienKS = {{plate}} &
Xe= {{type}} &
captcha = {{captcha}} &
ipClient = 9.9.9.91 &
cUrl = 1

### Get violations
POST https://www.csgt.vn/tra-cuu-phuong-tien-vi-pham.html?
     &LoaiXe={{vehicle_type}}&
     BienKiemSoat={{plate}}
